### ISSUE TITLE
Shader compile error on android.

### ISSUE THREAD

**Issue by mdrunk** [miguel12345/UnityGradientBackground#1]
When deploying camera shader to android device, I get a shader compiler error.

Unity: 2017.3.1f1
Compiler: Gradle or internal
Android: Marshmallow.  Min API: 4.1 or 6.0
Error Log Attached

[shader_error_log.txt](https://github.com/miguel12345/UnityGradientBackground/files/1800706/shader_error_log.txt)

**Comment by miguel12345** [comment]
Hi,

That problem has been fixed in the latest commit. Can you let me know if it works for you?

Thanks for reporting the issue

**Comment by mdrunk** [comment]
Looks like the changes worked!  Be sure to re-make the package.

**Comment by miguel12345** [comment]
Thanks! I did forget to update it :P
